/* Style */
String style =
"<style>#file-input,input{width:100%;height:44px;border-radius:4px;margin:10px auto;font-size:15px}"
".container { width: 35%; margin: auto; padding: 10px; background-color: whitesmoke; border-radius: 10px; padding: 25px 0 35px 0; }"
"input{background:#f1f1f1;border:0;padding: 5px}body{background:#636f82;font-family:sans-serif;font-size:14px;color:#777}"
"#psw { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-size: normal; font-weight: normal; width: auto; margin: none; border: none;"
"outline: none; border-radius: 4px; background-color: white; padding-left: 1%; height: 30px; width: 48%; border: 1px solid dodgerblue; }"
"#file-input{padding:0; text-align:center; display:block; cursor:pointer}"
"#bar,#prgbar{background-color:#f1f1f1;border-radius:10px}#bar{background-color:#3498db;width:0%;height:10px}"
"form{background:#fff;max-width:258px;margin:75px auto;padding:30px;border-radius:5px;text-align:center}"
".btn { color: #333; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-size: normal;"
"font-weight: normal; width: auto; margin: none; border: none; outline: none; border-radius: 4px; background-color: white; height: 30px; width: 25%; border: 1px solid dodgerblue; }"
".btn:hover { color: white; width: 50%; transition: all .2s ease-in-out; transform: scale(1); background: dodgerblue; }";


 
/* Server Index Page */
String updatePage = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
"<input type='file' name='update' id='file' onchange='sub(this)' style=display:none>"
"<label id='file-input' for='file'>   Choose file...</label>"
"<input type='password' name='password' id='psw' placeholder = 'Password'> <br>"
"<input type='submit' class=btn value='Update'>"
"<br><br>"
"<div id='prg'></div>"
"<br><div id='prgbar'><div id='bar'></div></div><br></form>"
"<script>"
  "function sub(obj){"
"var fileName = obj.value.split('\\\\');"
"document.getElementById('file-input').innerHTML = '   '+ fileName[fileName.length-1];"
"};"
  "$('form').submit(function(e){"
"e.preventDefault();"
"var form = $('#upload_form')[0];"
"var data = new FormData(form);"
  "if(form.psw.value=='197346')"
"{"
"form.psw.value = '';"
"$.ajax({"
"url: '/update',"
"type: 'POST',"
"data: data,"
"contentType: false,"
"processData:false,"
"xhr: function() {"
"var xhr = new window.XMLHttpRequest();"
"xhr.upload.addEventListener('progress', function(evt) {"
"if (evt.lengthComputable) {"
"var per = evt.loaded / evt.total;"
"$('#prg').html('progress: ' + Math.round(per*100) + '%');"
"$('#bar').css('width',Math.round(per*100) + '%');"
"}"
"}, false);"
"return xhr;"
"},"
"success:function(d, s) {"
"console.log('success!') "
"},"
"error: function (a, b, c) {"
"}"
"});"
"}"
  "else"
"{"
" alert('Error: Password Incorrect')/*displays error message*/"
"}"
"});"
"</script>" + style;
